name: Overlay QA using pkgcheck

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'scripts/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'scripts/**'
  schedule:
    - cron: "0 6 * * 1"

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Run pkgcheck
      uses: pkgcore/pkgcheck-action@v1
