name: Overlay QA using pkgcheck

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'scripts/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'scripts/**'
  schedule:
    - cron: "0 6 * * 1"

# Declare default permissions as read only.
permissions: read-all

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Run pkgcheck
      uses: pkgcore/pkgcheck-action@16edefb00ef1485e2eb2bfd3d93a70b198b2537f # No releases, v1 branch
      with:
        args: 'app-arch app-misc dev-python dev-util sys-apps sys-auth sys-cluster sys-fabric'
